name: city_tales_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  http:
  get:
  flutter_svg:
  geolocator:
  geocoding:
  google_maps_flutter:
  flutter_typeahead:
  google_places_flutter: any
  image_picker: 
  dio: ^5.7.0
  arkit_plugin: ^1.1.1  
  ar_flutter_plugin: 




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/
